import type { Product } from "@/lib/product";

export const MOCK_PRODUCTS: Product[] = [
  {
    id: "prd_001",
    name: "Laptop Acme Pro 14",
    sku: "ACMLP14",
    description: "Lekki laptop biznesowy z ekranem 14 cali.",
    manufacturer: "acme",
    category: "electronics",
    features: ["bestseller", "new"],
    netPrice: 4999,
    grossPrice: 6148.77,
    vatRate: 23,
    currency: "PLN",
    isAvailable: true,
    isLimited: false,
    minOrderQuantity: 1,
    maxOrderQuantity: 5,
  },
  {
    id: "prd_002",
    name: "Smartfon Globex X",
    sku: "GLBXS20",
    manufacturer: "globex",
    category: "electronics",
    features: ["new"],
    netPrice: 200,
    grossPrice: 216,
    vatRate: 8,
    currency: "PLN",
    isAvailable: true,
    isLimited: true,
    stockQuantity: 120,
    minOrderQuantity: 1,
    maxOrderQuantity: 10,
  },
  {
    id: "prd_003",
    name: "Koszulka Initech Basic",
    sku: "INTCBASIC",
    description: "Bawełniana koszulka z kolekcji podstawowej.",
    manufacturer: "initech",
    category: "clothing",
    features: ["eco-friendly"],
    netPrice: 150,
    grossPrice: 150,
    vatRate: 0,
    currency: "EUR",
    isAvailable: true,
    isLimited: false,
    minOrderQuantity: 1,
    maxOrderQuantity: 50,
  },
  {
    id: "prd_004",
    name: "Ekspres Umbrella Barista",
    sku: "UMBBAR1",
    manufacturer: "umbrella",
    category: "home",
    features: ["bestseller", "discounted"],
    netPrice: 100,
    grossPrice: 105,
    vatRate: 5,
    currency: "PLN",
    isAvailable: true,
    isLimited: false,
    minOrderQuantity: 1,
    maxOrderQuantity: 8,
  },
  {
    id: "prd_005",
    name: "Rower Acme Trail",
    sku: "ACMTRL9",
    manufacturer: "acme",
    category: "sports",
    features: ["eco-friendly", "new"],
    netPrice: 320,
    grossPrice: 393.6,
    vatRate: 23,
    currency: "PLN",
    isAvailable: false,
    isLimited: false,
    minOrderQuantity: 1,
    maxOrderQuantity: 3,
  },
  {
    id: "prd_006",
    name: "Słuchawki Globex Air",
    sku: "GLBAIR7",
    manufacturer: "globex",
    category: "electronics",
    features: ["discounted"],
    netPrice: 59,
    grossPrice: 63.72,
    vatRate: 8,
    currency: "PLN",
    isAvailable: true,
    isLimited: true,
    stockQuantity: 0,
    minOrderQuantity: 1,
    maxOrderQuantity: 4,
  },
  {
    id: "prd_007",
    name: "Bluza Initech Team",
    sku: "INTCTEAM",
    description: "Limitowana bluza z haftem zespołu.",
    manufacturer: "initech",
    category: "clothing",
    features: ["limited-edition"],
    netPrice: 35.2,
    grossPrice: 36.96,
    vatRate: 5,
    currency: "EUR",
    isAvailable: true,
    isLimited: true,
    stockQuantity: 25,
    minOrderQuantity: 1,
    maxOrderQuantity: 20,
  },
  {
    id: "prd_008",
    name: "Monitor Umbrella Vision",
    sku: "UMBVSN27",
    manufacturer: "umbrella",
    category: "electronics",
    features: ["new"],
    netPrice: 999,
    grossPrice: 1228.77,
    vatRate: 23,
    currency: "PLN",
    isAvailable: true,
    isLimited: false,
    minOrderQuantity: 1,
    maxOrderQuantity: 6,
  },
  {
    id: "prd_009",
    name: "Mata do jogi Acme Flow",
    sku: "ACMFLOW2",
    manufacturer: "acme",
    category: "sports",
    features: ["eco-friendly", "bestseller"],
    netPrice: 45,
    grossPrice: 55.35,
    vatRate: 23,
    currency: "PLN",
    isAvailable: true,
    isLimited: false,
    minOrderQuantity: 2,
    maxOrderQuantity: 30,
  },
  {
    id: "prd_010",
    name: "Kubek Globex Ceramic",
    sku: "GLBCER1",
    manufacturer: "globex",
    category: "home",
    features: ["discounted"],
    netPrice: 12,
    grossPrice: 12.96,
    vatRate: 8,
    currency: "PLN",
    isAvailable: true,
    isLimited: true,
    stockQuantity: 340,
    minOrderQuantity: 1,
    maxOrderQuantity: 100,
  },
  {
    id: "prd_011",
    name: "Klawiatura Initech Mech",
    sku: "INTCMECH",
    manufacturer: "initech",
    category: "electronics",
    features: ["new", "bestseller"],
    netPrice: 75,
    grossPrice: 92.25,
    vatRate: 23,
    currency: "PLN",
    isAvailable: true,
    isLimited: false,
    minOrderQuantity: 1,
    maxOrderQuantity: 12,
  },
  {
    id: "prd_012",
    name: "Plecak Umbrella Urban",
    sku: "UMBURB1",
    manufacturer: "umbrella",
    category: "clothing",
    features: ["eco-friendly"],
    netPrice: 60,
    grossPrice: 63,
    vatRate: 5,
    currency: "USD",
    isAvailable: true,
    isLimited: false,
    minOrderQuantity: 1,
    maxOrderQuantity: 15,
  },
  {
    id: "prd_013",
    name: "Telewizor Acme Cinema 55",
    sku: "ACMCIN55",
    description: "Telewizor 4K z panelem OLED.",
    manufacturer: "acme",
    category: "electronics",
    features: ["bestseller"],
    netPrice: 1250,
    grossPrice: 1537.5,
    vatRate: 23,
    currency: "PLN",
    isAvailable: true,
    isLimited: true,
    stockQuantity: 8,
    minOrderQuantity: 1,
    maxOrderQuantity: 2,
  },
  {
    id: "prd_014",
    name: "Notatnik Globex Soft",
    sku: "GLBSOFT",
    manufacturer: "globex",
    category: "home",
    features: ["discounted", "eco-friendly"],
    netPrice: 4,
    grossPrice: 4.92,
    vatRate: 23,
    currency: "PLN",
    isAvailable: true,
    isLimited: false,
    minOrderQuantity: 1,
    maxOrderQuantity: 200,
  },
  {
    id: "prd_015",
    name: "Skarpetki Initech Sport",
    sku: "INTCSPRT",
    manufacturer: "initech",
    category: "sports",
    features: ["bestseller"],
    netPrice: 30,
    grossPrice: 32.4,
    vatRate: 8,
    currency: "PLN",
    isAvailable: true,
    isLimited: false,
    minOrderQuantity: 3,
    maxOrderQuantity: 50,
  },
];
