import type { Product } from "@/lib/product";

export const MOCK_PRODUCTS: Product[] = [
  {
    id: "prd_001",
    name: "Laptop Acme Pro 14",
    sku: "ACMLP14",
    description: "Lekki laptop biznesowy z ekranem 14 cali.",
    manufacturer: "acme",
    category: "electronics",
    features: ["bestseller", "new"],
    netPrice: 4999,
    grossPrice: 6148.77,
    vatRate: 23,
    currency: "PLN",
    isAvailable: true,
    isLimited: false,
    minOrderQuantity: 1,
    maxOrderQuantity: 5,
  },
  {
    id: "prd_002",
    name: "Smartfon Globex X",
    sku: "GLBXS20",
    manufacturer: "globex",
    category: "electronics",
    features: ["new"],
    netPrice: 200,
    grossPrice: 216,
    vatRate: 8,
    currency: "PLN",
    isAvailable: true,
    isLimited: true,
    stockQuantity: 120,
    minOrderQuantity: 1,
    maxOrderQuantity: 10,
  },
  {
    id: "prd_003",
    name: "Koszulka Initech Basic",
    sku: "INTCBASIC",
    description: "Bawełniana koszulka z kolekcji podstawowej.",
    manufacturer: "initech",
    category: "clothing",
    features: ["eco-friendly"],
    netPrice: 150,
    grossPrice: 150,
    vatRate: 0,
    currency: "EUR",
    isAvailable: true,
    isLimited: false,
    minOrderQuantity: 1,
    maxOrderQuantity: 50,
  },
  {
    id: "prd_004",
    name: "Ekspres Umbrella Barista",
    sku: "UMBBAR1",
    manufacturer: "umbrella",
    category: "home",
    features: ["bestseller", "discounted"],
    netPrice: 100,
    grossPrice: 105,
    vatRate: 5,
    currency: "PLN",
    isAvailable: true,
    isLimited: false,
    minOrderQuantity: 1,
    maxOrderQuantity: 8,
  },
  {
    id: "prd_005",
    name: "Rower Acme Trail",
    sku: "ACMTRL9",
    manufacturer: "acme",
    category: "sports",
    features: ["eco-friendly", "new"],
    netPrice: 320,
    grossPrice: 393.6,
    vatRate: 23,
    currency: "PLN",
    isAvailable: false,
    isLimited: false,
    minOrderQuantity: 1,
    maxOrderQuantity: 3,
  },
];
